@MyWebApi_HostAddress = http://localhost:5284
@MyWebApi_HostAddress_HTTPS = https://localhost:7102

GET {{MyWebApi_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{MyWebApi_HostAddress_HTTPS}}/weatherforecast/
Accept: application/json
###
